"""R3 physical access: segmented line taps, the custom cells, and the W-blind placement plan.

  * every line L gets K taps lt_L_s0..s{K-1} (two-site cell LTAP2) on the SAME base net L; the base routes the
    line as a W-independent spine (met1-met3) from its driver through its taps;
  * rows are split into K equal segments; a program connects a site in segment s only to its line's tap in
    segment s (programs.py);
  * placement plan (FIRM before global placement, ORFS POST_PDN_TCL): one band per block (ubp) or per input
    (g1, pc2); the band's via sites in one track-aligned column at the band centre, row i at height (i + 0.5)/m;
    tap (line t of the band's T lines, segment s) at height (s + (t + 0.5)/T)/K, x = (t + 0.5)/T of the band.
Everything depends only on (row, band, line index, segment): the same base serves every W.
Cell text (LTAP2 LEF, via-site LEF/Liberty) and the placer TCL are the validated R3 ones (_legacy).
"""
from __future__ import annotations

import re
import shutil
from pathlib import Path

from . import arch
from ._legacy import DONT_TOUCH_R3, R3_PLACER, g2_cells_main, r3_build

TAP_RE = re.compile(r'  LTAP (lt_(\w+)) \(\n    \.A\((\w+)\)\n  \);\n')
RES = Path(__file__).resolve().parent / 'resources'


def expand(cfg, root: Path) -> Path:
    """netlist_logic.v (one abstract LTAP per line) -> netlist_base.v (K LTAP2 taps per line)."""
    nd = root / 'netlist'
    net = (nd / 'netlist_logic.v').read_text()
    n_old = len(TAP_RE.findall(net))
    K = cfg.K

    def rep(m):
        return ''.join(f'  LTAP2 {m.group(1)}_s{s} (\n    .A({m.group(3)})\n  );\n' for s in range(K))
    net2 = TAP_RE.sub(rep, net)
    n_lines = len(arch.lines(cfg))
    if not (n_old == n_lines and net2.count('LTAP2 lt_') == n_lines * K and ' LTAP lt_' not in net2):
        raise RuntimeError(f'access expansion: {n_old} taps found for {n_lines} lines')
    out = nd / 'netlist_base.v'
    out.write_text(net2)
    return out


def write_cells(root: Path):
    """cells/: via sites + LTAP (G2), LTAP2 + dont_touch (R3), and the met1-rail PDN (D-G2.2)."""
    cd = root / 'cells'
    g2_cells_main(cd)
    r3_build.cells(root)                       # writes root/cells/g2r3_cells.{lef,lib}, dont_touch_r3.tcl
    assert (cd / 'dont_touch_r3.tcl').read_text() == DONT_TOUCH_R3
    shutil.copy(RES / 'pdn_m1rails.tcl', cd / 'pdn_m1rails.tcl')


def plan_entries(cfg, netlist_base: str) -> list[tuple[str, int, float, float]]:
    """(instance, band, x fraction within band, y fraction of core), in placement order."""
    K, m = cfg.K, cfg.m
    plan = []
    for i, k in re.findall(r'VSITE_BUF vs_(\d+)_(\d+) ', netlist_base):
        plan.append((f'vs_{i}_{k}', int(k), 0.5, (int(i) + 0.5) / m))
    for b, lines in arch.band_lines(cfg).items():
        T = len(lines)
        for t, L in enumerate(lines):
            for s in range(K):
                plan.append((f'lt_{L}_s{s}', b, (t + 0.5) / T, (s + (t + 0.5) / T) / K))
    return plan


def write_plan(cfg, root: Path) -> Path:
    net = (root / 'netlist' / 'netlist_base.v').read_text()
    plan = plan_entries(cfg, net)
    nb = len(arch.band_lines(cfg))
    tcl = [f'# generated by ubpgen for {cfg.name}: {nb} bands, {len(plan)} cells (sites + {cfg.K} taps per line)',
           f'set r3_nb {nb}', 'set r3_plan {']
    tcl += [f'  {{{n} {b} {xf:.6f} {yf:.6f}}}' for n, b, xf, yf in plan]
    tcl += ['}', R3_PLACER]
    ld = root / 'layout'
    ld.mkdir(exist_ok=True)
    out = ld / 'place_access.tcl'
    out.write_text('\n'.join(tcl) + '\n')
    return out


def parse_plan(tcl_text: str) -> list[tuple[str, int, str, str]]:
    return re.findall(r'^  \{(\S+) (\d+) ([\d.]+) ([\d.]+)\}$', tcl_text, flags=re.M)
