/* Generated by Yosys 0.69+ (git sha1 e8db64c60, Release, Clang /usr/bin/clang++ 18.1.3) */

module top(y, clk, wire4);
  output [1:0] y;
  wire [1:0] y;
  input clk;
  wire clk;
  input signed wire4;
  wire signed wire4;
  wire [1:0] reg10;
  reg \reg10_reg[0]  = 1'h0;
  always @(posedge clk)
    \reg10_reg[0]  <= wire4;
  assign reg10[0] = \reg10_reg[0] ;
  assign reg10[1] = reg10[0];
  assign y = { reg10[0], reg10[0] };
endmodule
