/* Generated by Yosys 0.8 (git sha1 5706e90, clang 14.0.0-1ubuntu1.1 -fPIC -Os) */

module top(y, clk, wire4);
  input clk;
  wire [1:0] reg10;
  input wire4;
  output [1:0] y;
  reg \reg10_reg[0]  = 1'h0;
  always @(posedge clk)
      \reg10_reg[0]  <= wire4;
  assign reg10[0] = \reg10_reg[0] ;
  assign reg10[1] = reg10[0];
  assign y = { reg10[0], reg10[0] };
endmodule
