// Generated by PassWitness. Do not use as a golden design.
module passwitness_miter(
    input signed [3:0] a,
    input signed [3:0] b,
    output mismatch,
    output signed [19:0] reference_y,
    output signed [19:0] candidate_y);
    fma_impl gold(.a(a), .b(b), .y(reference_y));
    passwitness_candidate candidate(.a(a), .b(b), .y(candidate_y));
    assign mismatch = |(reference_y ^ candidate_y);
endmodule
