from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Iterable

from .models import Port


_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_$]*$")
_MODEL_LINE = re.compile(
    r"^\s*\\?([A-Za-z_][A-Za-z0-9_$]*)\s+(-?\d+)\s+([0-9a-fA-F]+)\s+([01xXzZ?]+)\s*$"
)


def load_ports(metadata_path: Path, top: str) -> list[Port]:
    data = json.loads(metadata_path.read_text(encoding="utf-8"))
    module = data.get("modules", {}).get(top)
    if not module:
        raise ValueError(f"Yosys metadata does not contain top module {top!r}")
    ports: list[Port] = []
    for name, info in module.get("ports", {}).items():
        direction = info.get("direction")
        if direction not in {"input", "output"}:
            raise ValueError(f"Port {name!r} has unsupported direction {direction!r}")
        if not _IDENTIFIER.fullmatch(name):
            raise ValueError(f"Port name {name!r} is not supported by the Phase 1 miter generator")
        bits = info.get("bits", [])
        if not bits:
            raise ValueError(f"Port {name!r} has zero width")
        ports.append(Port(name=name, direction=direction, width=len(bits), signed=bool(info.get("signed", 0))))
    if not ports or not any(port.direction == "input" for port in ports):
        raise ValueError("The top module must have at least one input")
    if not any(port.direction == "output" for port in ports):
        raise ValueError("The top module must have at least one output")
    return ports


def module_is_sequential(metadata_path: Path, top: str) -> bool:
    data = json.loads(metadata_path.read_text(encoding="utf-8"))
    module = data["modules"][top]
    sequential_prefixes = ("$dff", "$adff", "$aldff", "$dffe", "$dlatch", "$mem")
    return any(str(cell.get("type", "")).startswith(sequential_prefixes) for cell in module.get("cells", {}).values())


def port_correspondence_errors(expected: Iterable[Port], actual: Iterable[Port]) -> list[str]:
    """Return explicit golden/candidate interface mismatches."""
    expected_by_name = {port.name: port for port in expected}
    actual_by_name = {port.name: port for port in actual}
    errors: list[str] = []
    for name in sorted(expected_by_name.keys() - actual_by_name.keys()):
        errors.append(f"candidate is missing port {name!r}")
    for name in sorted(actual_by_name.keys() - expected_by_name.keys()):
        errors.append(f"candidate has unexpected port {name!r}")
    for name in sorted(expected_by_name.keys() & actual_by_name.keys()):
        gold = expected_by_name[name]
        candidate = actual_by_name[name]
        if gold.direction != candidate.direction:
            errors.append(f"port {name!r} direction differs: {gold.direction} != {candidate.direction}")
        if gold.width != candidate.width:
            errors.append(f"port {name!r} width differs: {gold.width} != {candidate.width}")
        if gold.signed != candidate.signed:
            errors.append(f"port {name!r} signedness differs: {gold.signed} != {candidate.signed}")
    return errors


def _decl(port: Port, name: str, direction: str | None = None) -> str:
    direction = direction or port.direction
    signed = " signed" if port.signed else ""
    range_text = f"[{port.width - 1}:0] " if port.width > 1 else ""
    return f"{direction}{signed} {range_text}{name}".strip()


def _parameter_override(parameters: dict[str, str]) -> str:
    if not parameters:
        return ""
    return " #(" + ", ".join(f".{name}({value})" for name, value in parameters.items()) + ")"


def write_miter(
    path: Path,
    top: str,
    ports: Iterable[Port],
    parameters: dict[str, str],
    *,
    reference_module: str | None = None,
    candidate_module: str = "passwitness_candidate",
) -> None:
    ports = list(ports)
    inputs = [port for port in ports if port.direction == "input"]
    outputs = [port for port in ports if port.direction == "output"]
    lines = ["// Generated by PassWitness. Do not use as a golden design.", "module passwitness_miter("]
    declarations = [_decl(port, port.name, "input") for port in inputs]
    declarations.append("output mismatch")
    for port in outputs:
        declarations.append(_decl(port, f"reference_{port.name}", "output"))
        declarations.append(_decl(port, f"candidate_{port.name}", "output"))
    lines.append("    " + ",\n    ".join(declarations) + ");")
    input_connections = ", ".join(f".{port.name}({port.name})" for port in inputs)
    gold_connections = input_connections + (", " if input_connections else "") + ", ".join(
        f".{port.name}(reference_{port.name})" for port in outputs
    )
    candidate_connections = input_connections + (", " if input_connections else "") + ", ".join(
        f".{port.name}(candidate_{port.name})" for port in outputs
    )
    override = _parameter_override(parameters)
    reference_module = reference_module or top
    lines.append(f"    {reference_module}{override} gold({gold_connections});")
    lines.append(f"    {candidate_module} candidate({candidate_connections});")
    mismatch_terms = " | ".join(f"|(reference_{port.name} ^ candidate_{port.name})" for port in outputs)
    lines.append(f"    assign mismatch = {mismatch_terms};")
    lines.append("endmodule")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_model(log: str) -> dict[str, dict[str, str | int]]:
    model: dict[str, dict[str, str | int]] = {}
    for line in log.splitlines():
        match = _MODEL_LINE.match(line)
        if match:
            name, decimal, hexa, binary = match.groups()
            model[name] = {"decimal": int(decimal), "hex": hexa, "binary": binary}
    return model


def counterexample_from_model(model: dict[str, dict[str, str | int]], ports: Iterable[Port]) -> dict:
    ports = list(ports)
    inputs = {port.name: model[port.name] for port in ports if port.direction == "input" and port.name in model}
    reference = {
        port.name: model[f"reference_{port.name}"]
        for port in ports
        if port.direction == "output" and f"reference_{port.name}" in model
    }
    candidate = {
        port.name: model[f"candidate_{port.name}"]
        for port in ports
        if port.direction == "output" and f"candidate_{port.name}" in model
    }
    return {"inputs": inputs, "reference_outputs": reference, "candidate_outputs": candidate, "raw_model": model}
